/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDemoLargeRouteImport } from './routes/_authenticated/demo-large'
import { Route as ApiDemoIssuesRouteImport } from './routes/api/demo-issues'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiTodosRouteImport } from './routes/api/todos'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as AuthenticatedDemoBeforeIndexRouteImport } from './routes/_authenticated/demo-before/index'
import { Route as AuthenticatedDemoBeforeProjectIdRouteImport } from './routes/_authenticated/demo-before/$projectId'
import { Route as AuthenticatedProjectProjectIdRouteImport } from './routes/_authenticated/project/$projectId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemoLargeRoute = AuthenticatedDemoLargeRouteImport.update({
  id: '/demo-large',
  path: '/demo-large',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiDemoIssuesRoute = ApiDemoIssuesRouteImport.update({
  id: '/api/demo-issues',
  path: '/api/demo-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosRoute = ApiTodosRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDemoBeforeIndexRoute =
  AuthenticatedDemoBeforeIndexRouteImport.update({
    id: '/demo-before/',
    path: '/demo-before/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemoBeforeProjectIdRoute =
  AuthenticatedDemoBeforeProjectIdRouteImport.update({
    id: '/demo-before/$projectId',
    path: '/demo-before/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectProjectIdRoute =
  AuthenticatedProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/demo-large': typeof AuthenticatedDemoLargeRoute
  '/api/demo-issues': typeof ApiDemoIssuesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/todos': typeof ApiTodosRoute
  '/api/users': typeof ApiUsersRoute
  '/demo-before/$projectId': typeof AuthenticatedDemoBeforeProjectIdRoute
  '/project/$projectId': typeof AuthenticatedProjectProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo-before/': typeof AuthenticatedDemoBeforeIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/demo-large': typeof AuthenticatedDemoLargeRoute
  '/api/demo-issues': typeof ApiDemoIssuesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/todos': typeof ApiTodosRoute
  '/api/users': typeof ApiUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/demo-before/$projectId': typeof AuthenticatedDemoBeforeProjectIdRoute
  '/project/$projectId': typeof AuthenticatedProjectProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo-before': typeof AuthenticatedDemoBeforeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/demo-large': typeof AuthenticatedDemoLargeRoute
  '/api/demo-issues': typeof ApiDemoIssuesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/todos': typeof ApiTodosRoute
  '/api/users': typeof ApiUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/demo-before/$projectId': typeof AuthenticatedDemoBeforeProjectIdRoute
  '/_authenticated/project/$projectId': typeof AuthenticatedProjectProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/demo-before/': typeof AuthenticatedDemoBeforeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/demo-large'
    | '/api/demo-issues'
    | '/api/projects'
    | '/api/todos'
    | '/api/users'
    | '/demo-before/$projectId'
    | '/project/$projectId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/demo-before/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/demo-large'
    | '/api/demo-issues'
    | '/api/projects'
    | '/api/todos'
    | '/api/users'
    | '/'
    | '/demo-before/$projectId'
    | '/project/$projectId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/demo-before'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/demo-large'
    | '/api/demo-issues'
    | '/api/projects'
    | '/api/todos'
    | '/api/users'
    | '/_authenticated/'
    | '/_authenticated/demo-before/$projectId'
    | '/_authenticated/project/$projectId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authenticated/demo-before/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiDemoIssuesRoute: typeof ApiDemoIssuesRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiTodosRoute: typeof ApiTodosRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo-large': {
      id: '/_authenticated/demo-large'
      path: '/demo-large'
      fullPath: '/demo-large'
      preLoaderRoute: typeof AuthenticatedDemoLargeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/demo-issues': {
      id: '/api/demo-issues'
      path: '/api/demo-issues'
      fullPath: '/api/demo-issues'
      preLoaderRoute: typeof ApiDemoIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/demo-before/': {
      id: '/_authenticated/demo-before/'
      path: '/demo-before'
      fullPath: '/demo-before/'
      preLoaderRoute: typeof AuthenticatedDemoBeforeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo-before/$projectId': {
      id: '/_authenticated/demo-before/$projectId'
      path: '/demo-before/$projectId'
      fullPath: '/demo-before/$projectId'
      preLoaderRoute: typeof AuthenticatedDemoBeforeProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/$projectId': {
      id: '/_authenticated/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDemoLargeRoute: typeof AuthenticatedDemoLargeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDemoBeforeProjectIdRoute: typeof AuthenticatedDemoBeforeProjectIdRoute
  AuthenticatedProjectProjectIdRoute: typeof AuthenticatedProjectProjectIdRoute
  AuthenticatedDemoBeforeIndexRoute: typeof AuthenticatedDemoBeforeIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDemoLargeRoute: AuthenticatedDemoLargeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDemoBeforeProjectIdRoute: AuthenticatedDemoBeforeProjectIdRoute,
  AuthenticatedProjectProjectIdRoute: AuthenticatedProjectProjectIdRoute,
  AuthenticatedDemoBeforeIndexRoute: AuthenticatedDemoBeforeIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiDemoIssuesRoute: ApiDemoIssuesRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiTodosRoute: ApiTodosRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
